Update admin.py
Newer versions of Django no-longer include `update_wrapper`, as it's expected to be provided in the language's standard library.

Here's the error I was getting as of now:

      File "/usr/lib/python2.7/site-packages/singleton_models/admin.py", line 5, in <module>
        from django.utils.functional import update_wrapper
    ImportError: cannot import name update_wrapper

My environment is: Django 1.6.2 final, and Python 2.7.6